"""add_last_collected_at

Revision ID: 413b898c209e
Revises: ad9fde8a3a55
Create Date: 2026-05-13 10:02:32.680080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413b898c209e'
down_revision: Union[str, None] = 'ad9fde8a3a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    op.add_column('devices', sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_collected_at')
    op.create_table('site_settings',
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='site_settings_pkey')
    )
    # ### end Alembic commands ###
